# pandas 미니 퀘스트

In [ ]:
import numpy as np
import pandas as pd

## 시리즈 - 미니 퀘스트

### 1번 퀘스트

In [ ]:
series = pd.Series([5, 10, 15, 20])

print(series.index)

RangeIndex(start=0, stop=4, step=1)

### 2번 퀘스트

In [69]:
data = {'a': 100, 'b': 200, 'c': 300}

series = pd.Series(data)
print(series["b"])

200

### 3번 퀘스트

In [70]:
series = pd.Series([1, 2, None, 4, None, 6])

series.isnull()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [71]:
series.fillna(0)

0    1.0
1    2.0
2    0.0
3    4.0
4    0.0
5    6.0
dtype: float64

## 데이터프레임 - 미니 퀘스트

### 1번 퀘스트

In [72]:
data = {'이름': ['홍길동', '김철수', '박영희'], 
        '나이': [25, 30, 28], 
        '성별': ['남', '남', '여']}
df = pd.DataFrame(data)

df.columns

Index(['이름', '나이', '성별'], dtype='str')

### 2번 퀘스트

In [73]:
data = {'이름': ['홍길동', '김철수', '박영희'], 
        '나이': [25, 30, 28], 
        '성별': ['남', '남', '여']}
df = pd.DataFrame(data)

df.sort_values("나이")

    이름  나이 성별
0  홍길동  25  남
2  박영희  28  여
1  김철수  30  남

### 3번 퀘스트

In [74]:
data = {'이름': ['홍길동', '김철수', '박영희', '이순신'], 
        '국어': [85, 90, 88, 92], 
        '영어': [78, 85, 89, 87], 
        '수학': [92, 88, 84, 90]}
df = pd.DataFrame(data)

df["총점"] = df["국어"] + df["영어"] + df["수학"]
df[df["총점"] >= 250]

    이름  국어  영어  수학   총점
0  홍길동  85  78  92  255
1  김철수  90  85  88  263
2  박영희  88  89  84  261
3  이순신  92  87  90  269

## 필터링 - 미니 퀘스트

### 1번 퀘스트

In [75]:
data = {'이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
        '나이': [25, 30, 35, 40, 45],
        '도시': ['서울', '부산', '서울', '대구', '부산']}
df = pd.DataFrame(data)

df[df["나이"] >= 30]

    이름  나이  도시
1  김철수  30  부산
2  박영희  35  서울
3  이순신  40  대구
4  강감찬  45  부산

### 2번 퀘스트

In [76]:
data = {'이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
        '나이': [25, 30, 35, 40, 45],
        '도시': ['서울', '부산', '서울', '대구', '부산'],
        '점수': [85, 90, 75, 95, 80]}
df = pd.DataFrame(data)

df[(df["도시"] == "서울") & (df["점수"] >= 80)]

    이름  나이  도시  점수
0  홍길동  25  서울  85

### 3번 퀘스트

In [77]:
data = {'이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬'],
        '나이': [25, 30, 35, 40, 45],
        '도시': ['서울', '부산', '서울', '대구', '부산'],
        '점수': [85, 90, 75, 95, 80]}
df = pd.DataFrame(data)

df.query("나이 >= 35 and 점수 > 80")

    이름  나이  도시  점수
3  이순신  40  대구  95

## 그룹화 - 미니 퀘스트

### 1번 퀘스트

In [78]:
data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신'],
    '부서': ['영업', '영업', '인사', '인사'],
    '급여': [5000, 5500, 4800, 5100]
}
df = pd.DataFrame(data)

df.groupby("부서")["급여"].sum()

부서
영업    10500
인사     9900
Name: 급여, dtype: int64

### 2번 퀘스트

In [79]:
data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당'],
    '부서': ['영업', '영업', '인사', '인사', 'IT', 'IT'],
    '급여': [5000, 5500, 4800, 5100, 6000, 6200]
}
df = pd.DataFrame(data)

df.groupby("부서")["급여"].agg(["sum", "mean"])

      sum    mean
부서
IT  12200  6100.0
영업  10500  5250.0
인사   9900  4950.0

### 3번 퀘스트

In [80]:
data = {
    '이름': ['홍길동', '김철수', '박영희', '이순신', '강감찬', '신사임당'],
    '부서': ['영업', '영업', '인사', '인사', 'IT', 'IT'],
    '급여': [5000, 5500, 4800, 5100, 6000, 6200]
}
df = pd.DataFrame(data)

df.groupby("부서").filter(lambda x: x["급여"].mean() >= 5000)

     이름  부서    급여
0   홍길동  영업  5000
1   김철수  영업  5500
4   강감찬  IT  6000
5  신사임당  IT  6200

## 병합 - 미니 퀘스트

### 1번 퀘스트

In [81]:
df1 = pd.DataFrame({'고객ID': [1, 2, 3], '이름': ['홍길동', '김철수', '이영희']})
df2 = pd.DataFrame({'고객ID': [2, 3, 4], '구매액': [10000, 20000, 30000]})

df = pd.merge(df1, df2, how="inner", on="고객ID")
df

   고객ID   이름    구매액
0     2  김철수  10000
1     3  이영희  20000

### 2번 퀘스트

In [82]:
df1 = pd.DataFrame({'고객ID': [1, 2, 3], '이름': ['홍길동', '김철수', '이영희']})
df2 = pd.DataFrame({'고객ID': [2, 3, 4], '구매액': [15000, 25000, 35000]})

df = pd.merge(df1, df2, how="left")
df

   고객ID   이름      구매액
0     1  홍길동      NaN
1     2  김철수  15000.0
2     3  이영희  25000.0

### 3번 퀘스트

In [83]:
df1 = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '도시': ['서울', '부산', '대전'],
    '구매액': [10000, 20000, 30000]
})
df2 = pd.DataFrame({
    '고객ID': [1, 2, 3],
    '도시': ['서울', '부산', '광주'],
    '구매액': [15000, 25000, 35000]
})

df = pd.merge(df1, df2, on=["고객ID", "도시"], suffixes=["_1", "_2"])
df

   고객ID  도시  구매액_1  구매액_2
0     1  서울  10000  15000
1     2  부산  20000  25000

## 결측치 처리 - 미니 퀘스트

### 1번 퀘스트

In [84]:

data = {'이름': ['홍길동', '김철수', np.nan, '이영희'],
        '나이': [25, np.nan, 30, 28],
        '성별': ['남', '남', '여', np.nan]}
df = pd.DataFrame(data)

print("[결측치 탐지]")
df.isnull()

[결측치 탐지]

      이름     나이     성별
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True

In [85]:
print("[열별 결측치 개수]")
df.isnull().sum(axis=0)

[열별 결측치 개수]

이름    1
나이    1
성별    1
dtype: int64

### 2번 퀘스트
주어진 데이터프레임에서 결측치가 포함된 행을 삭제하고, 새로운 데이터프레임을 출력하는 코드를 작성하세요.

In [86]:
data = {'이름': ['홍길동', '김철수', np.nan, '이영희'],
        '나이': [25, np.nan, 30, 28],
        '성별': ['남', '남', '여', np.nan]}
df = pd.DataFrame(data)

df.dropna(axis=0)

    이름    나이 성별
0  홍길동  25.0  남

### 3번 퀘스트
결측치가 포함된 '나이' 열을 평균값으로 대체하고, 새로운 데이터프레임을 출력하는 코드를 작성하세요.

In [87]:
data = {'이름': ['홍길동', '김철수', np.nan, '이영희'],
        '나이': [25, np.nan, 30, 28],
        '성별': ['남', '남', '여', np.nan]}
df = pd.DataFrame(data)

new_df = df.copy()
new_df["나이"] = df["나이"].fillna(df["나이"].mean())
new_df

    이름         나이   성별
0  홍길동  25.000000    남
1  김철수  27.666667    남
2  NaN  30.000000    여
3  이영희  28.000000  NaN

## 피벗 - 미니 퀘스트

### 1번 퀘스트
주어진 데이터프레임을 `pivot()` 함수를 사용하여 날짜(`날짜`)를 행 인덱스로, 제품(`제품`)을 열로, 판매량(`판매량`)을 값으로 설정하는 코드를 작성하세요.

In [88]:
data = {
    '날짜': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250]
}
df = pd.DataFrame(data)

df.pivot(index="날짜", columns="제품", values="판매량")

제품            A    B
날짜
2024-01-01  100  200
2024-01-02  150  250

### 2번 퀘스트
`pivot_table()`을 사용하여 주어진 데이터프레임에서 카테고리(`카테고리`)를 행 인덱스로, 제품(`제품`)을 열로 설정하고, 판매량(`판매량`)의 합계를 출력하는 코드를 작성하세요.

In [89]:
data = {
    '카테고리': ['전자', '가전', '전자', '가전'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250]
}
df = pd.DataFrame(data)

df.pivot_table(index="카테고리", columns="제품", values="판매량", aggfunc="sum", fill_value=0)

제품      A    B
카테고리
가전      0  450
전자    250    0

### 3번 퀘스트
주어진 데이터프레임에서 여러 값을 동시에 피벗하여, `pivot()`을 사용해 날짜(`날짜`)를 행으로, 제품(`제품`)을 열로 설정하고, 판매량(`판매량`)과 이익(`이익`)을 동시에 피벗하는 코드를 작성하세요.

In [90]:
data = {
    '날짜': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    '제품': ['A', 'B', 'A', 'B'],
    '판매량': [100, 200, 150, 250],
    '이익': [20, 50, 30, 60]
}
df = pd.DataFrame(data)

df.pivot(index="날짜", columns="제품", values=["판매량", "이익"])

            판매량       이익
제품            A    B   A   B
날짜
2024-01-01  100  200  20  50
2024-01-02  150  250  30  60

## 중복 제거 - 미니 퀘스트

### 1번 퀘스트
주어진 데이터프레임에서 기본적으로 중복된 행을 제거하는 코드를 작성하세요.

In [91]:
data = {
    '이름': ['김철수', '이영희', '김철수', '박민수'],
    '나이': [25, 30, 25, 40],
    '성별': ['남', '여', '남', '남']
}
df = pd.DataFrame(data)

df.drop_duplicates()

    이름  나이 성별
0  김철수  25  남
1  이영희  30  여
3  박민수  40  남

### 2번 퀘스트
다음 데이터프레임에서 특정 열을 기준으로 중복을 제거한 후, 중복 여부를 확인하는 코드를 작성하세요.

In [99]:
data = {
    '제품': ['노트북', '태블릿', '노트북', '스마트폰'],
    '가격': [1500000, 800000, 1500000, 1000000],
    '카테고리': ['전자기기', '전자기기', '전자기기', '전자기기']
}
df = pd.DataFrame(data)

for col in df.columns:
    print(f"[기준 열: {col}]")
    print(df.drop_duplicates(subset=[col]), end="\n\n")

[기준 열: 제품]
     제품       가격  카테고리
0   노트북  1500000  전자기기
1   태블릿   800000  전자기기
3  스마트폰  1000000  전자기기

[기준 열: 가격]
     제품       가격  카테고리
0   노트북  1500000  전자기기
1   태블릿   800000  전자기기
3  스마트폰  1000000  전자기기

[기준 열: 카테고리]
    제품       가격  카테고리
0  노트북  1500000  전자기기

### 3번 퀘스트
다음 데이터프레임에서 중복된 모든 행을 삭제한 후, 남은 데이터를 저장하고 다시 불러오는 코드를 작성하세요.

In [100]:
data = {
    '학생': ['김민수', '박지현', '김민수', '이정훈'],
    '성적': [90, 85, 90, 88],
    '학교': ['A고', 'B고', 'A고', 'C고']
}
df = pd.DataFrame(data)

df = df.drop_duplicates()
df

    학생  성적  학교
0  김민수  90  A고
1  박지현  85  B고
3  이정훈  88  C고

## 문자열 처리 - 미니 퀘스트

### 1번 퀘스트
Pandas의 `.str` 접근자를 사용하여 아래 시리즈의 모든 문자열을 소문자로 변환하는 코드를 작성하세요.

In [102]:
data = pd.Series(["HELLO", "WORLD", "PYTHON", "PANDAS"])

data.str.lower()

0     hello
1     world
2    python
3    pandas
dtype: str

### 2번 퀘스트
다음 데이터프레임에서 '이름' 컬럼의 문자열 앞뒤 공백을 제거하고, 특정 문자열 "Doe"가 포함된 행을 필터링하는 코드를 작성하세요.

In [103]:
df = pd.DataFrame({"이름": [" John Doe ", "Alice ", " Bob", "Charlie Doe "]})

df["이름"] = df["이름"].str.strip()
df[df["이름"].str.contains("Doe")]

            이름
0     John Doe
3  Charlie Doe

### 3번 퀘스트
아래 데이터프레임에서 '설명' 컬럼의 문자열을 공백을 기준으로 나누고, 각 단어의 첫 글자만 추출하여 새로운 컬럼 '약어'를 생성하는 코드를 작성하세요.

In [112]:
df = pd.DataFrame({"설명": ["빅데이터 분석", "데이터 과학", "머신 러닝", "딥 러닝"]})

def get_first_chars(words):
    return "".join([word[0] for word in words])

df["약어"] = df["설명"].str.split(" ").apply(get_first_chars)

df

        설명  약어
0  빅데이터 분석  빅분
1   데이터 과학  데과
2    머신 러닝  머러
3     딥 러닝  딥러